/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.sandraixchel.SonrisaDental.services;

import com.sandraixchel.SonrisaDental.exception.DateNotFoundException;
import com.sandraixchel.SonrisaDental.model.Appointment.AppointmentType;
import com.sandraixchel.SonrisaDental.repository.AppointmentRepository;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 *
 * @author Sandy
 */
@Service //Class to handle logic for checking apts
public class BookingService {

    private int[] possible_startTimes = {8, 9, 10, 11, 13, 14, 15, 16};

    @Autowired
    private AppointmentRepository appointmentRepository; //To inject the apt repo, it will be used to find existing apt in the data base

    //Lists all available apt slots. Returns a Map where the key is a date and the value is an Array List of available start times on that date
    public Map<String, ArrayList<String>> listAvailableAppointments(String selected_date, AppointmentType type) throws ParseException {

        //Create a new Map object, called free slots
        Map<String, ArrayList<String>> freeSlots = new HashMap<>();

        //String selected_date = "2023-07-17";  // Selected date by the user, passed by the front end
        //Creates a simpleDataFormat object, setting the format that the date object will have
        SimpleDateFormat date_formatter = new SimpleDateFormat("yyyy-MM-dd");

        //Creating a new calendar object at the current date and time
        Calendar cal = Calendar.getInstance();

        Date formattedDate = date_formatter.parse(selected_date); //Creates a date objectwith the value of selected_date, coverted from String
        cal.setTime(formattedDate);//takes in the date object with our selected date value

//        cal.setTime(date_formatter.parse(selected_date));
        //This code returns a time slot
        //Creates a date format object that will specify the format that the calendar object will have when converted to a String
        DateFormat time_formatter = new SimpleDateFormat("HH:mm");

        ArrayList<String> availableTimesForDay = new ArrayList<String>();//Initiate an ArrayList to store the available time for a day generated by the for loop

        for (int i = 0; i < possible_startTimes.length; i++) { //loop to go through the possible start times Array and return each value as "hour"
            //setting our calendar time to 8am for example
            int hour = possible_startTimes[i]; // each go throught the loop we want to set 'hour' to the value on the current index 

            cal.set(Calendar.HOUR_OF_DAY, hour);
            //To add the hour e.g. 8:00, 9:00, 10:00 etc
            cal.set(Calendar.MINUTE, 00);

            //Convert the calendar date (result of the cal.getTime method) to the formatted String (specified in time_formatter)
            String time = time_formatter.format(cal.getTime());

            if (timeSlotAvailable(cal, type)) {
                availableTimesForDay.add(time);
            }

            //To add the half hour e.g. 8:30, 9:30, 10:30 etc
            cal.set(Calendar.MINUTE, 30);
            //Convert the calendar object to the formatted String
            time = time_formatter.format(cal.getTime());

            if (timeSlotAvailable(cal, type)) {
                availableTimesForDay.add(time);
            }

        }

        //Adding data to the Map
        freeSlots.put(selected_date, availableTimesForDay);

        //Printing the content in the map
        return freeSlots;

    }

    public boolean timeSlotAvailable(Calendar cal, AppointmentType type) {

        Calendar end_timeApt = (Calendar) cal.clone();
        end_timeApt.add(Calendar.HOUR_OF_DAY, 1); // We just want to add an hour to the time of the copy of our calendar

        Calendar start_lunch = (Calendar) cal.clone();
        start_lunch.set(Calendar.HOUR_OF_DAY, 12);// Set the time when lunch starts at

        Calendar end_lunch = (Calendar) cal.clone();
        end_lunch.set(Calendar.HOUR_OF_DAY, 13);// Set the time when lunch ends at

        //If end time is between 12:00 and 13:00 pm, return false
        if (end_timeApt.after(start_lunch) && end_timeApt.before(end_lunch)) {

            return false;

            //Else return true 
        } else {
            return true;
        }

        //If time is after 17:00 pm, return false
        //If time clashes with any other appointment, retunr false
    }

}
